require('./globals.js')
var http = require('stream-http')
var crypto = require('react-native-crypto')
global.crypto = crypto
global.http = http

exports.assert						= require('assert/');
exports.buffer						= require('buffer/');
exports.child_process				= null;
exports.cluster						= null;
exports.console						= require('console-browserify');
exports.constants					= require('constants-browserify');
exports.crypto						= require('react-native-crypto');
exports.dgram						= null;
exports.dns							= null;
exports.domain						= require('domain-browser');
exports.events						= require('events/');
exports.fs							= null;
exports.http						= require('stream-http');
exports.https						= require('https-browserify');
exports.module						= null;
exports.net							= null;
exports.os							= require('os-browserify/browser.js');
exports.path						= require('path-browserify');
exports.punycode					= require('punycode/');
exports.process						= require('process/browser.js');
exports.querystring					= require('querystring-es3/');
exports.readline					= null;
exports.repl						= null;
exports.stream						= require('readable-stream');
exports._stream_duplex				= require('readable-stream/duplex.js');
exports._stream_passthrough			= require('readable-stream/passthrough.js');
exports._stream_readable			= require('readable-stream/readable.js');
exports._stream_transform			= require('readable-stream/transform.js');
exports._stream_writable			= require('readable-stream/writable.js');
exports.string_decoder				= require('string_decoder/');
exports.sys							= require('util/util.js');
exports.timers						= require('timers-browserify');
exports.tls							= null;
exports.tty							= require('tty-browserify');
exports.url							= require('url/');
exports.util						= require('util/util.js');
exports.vm							= null;
exports.zlib						= require('browserify-zlib');
